### ISSUE TITLE
build failed for Android

### ISSUE THREAD

**Issue by Ding34** [waffle-gl/waffle#41]
I put waffle in external directory in Android source tree, build Android framework, then run
$ m libwaffle-1
to build waffle for Android

build failed with error:

external/waffle/src/waffle/egl/wegl_context.c: In function 'create_real_context':
external/waffle/src/waffle/egl/wegl_context.c:102:40: error: 'EGL_CONTEXT_OPENGL_ROBUST_ACCESS' undeclared (first use in this function)
                     attrib_list[i++] = EGL_CONTEXT_OPENGL_ROBUST_ACCESS;
                                       ^
external/waffle/src/waffle/egl/wegl_context.c:102:40: note: each undeclared identifier is reported only once for each function it appears in

make: **\* [cm/out/target/product/generic/obj/SHARED_LIBRARIES/libwaffle-1_intermediates/src/waffle/egl/wegl_context.o] Error 1

**Comment by evelikov** [comment]
Hmm nice one thanks. Let me spin a patch.

**Comment by chadversary** [comment]
TODO: 
- [ ] Test the Android build. Close this issue if it succeeds.

**Comment by tpalli** [comment]
tested current master (dccb750) on oandroid-ia, builds ok!

**Comment by evelikov** [comment]
Closing as per Tapani's comment.
