### ISSUE TITLE
GBM doesn't work with newer mesa

### ISSUE THREAD

**Issue by dcbaker** [waffle-gl/waffle#43]
I noticed this recently, updating to waffle-git fixed the issue for me.

```
piglit: error: waffle_display_connect failed due to WAFFLE_ERROR_UNKNOWN: eglGetDisplay failed with error EGL_SUCCESS(0x3000)
```

**Comment by evelikov** [comment]
IIRC waffle-git uses the eglGetPlatformDisplay and upstream GLVND removed the GBM detection in eglGetDisplay. I have a patch for that somewhere let me fish it out and forward it accordingly.

**Comment by evelikov** [comment]
The following PR addresses the missing GBM detection and the typo in the EGL_PLATFORM string.

https://github.com/NVIDIA/libglvnd/pull/122

**Comment by evelikov** [comment]
PR has been merged - libglvnd is fixed ;-)
